### ISSUE TITLE
No permission to push

### ISSUE THREAD

**Issue by CryoKatOnIce** [ICESAT-2HackWeek/surface_classification#1]
After cloning the repo and creating my own branch, I tried to push to get my work onto git (two scripts which should appear in script folder), but I got an error. It looks like I maybe don't have permission to push?
Error:
remote: Permission to ICESAT-2HackWeek/surface_classification.git denied to CryoKatOnIce.
fatal: unable to access 'https://github.com/ICESAT-2HackWeek/surface_classification.git/': The requested URL returned error: 403

**Comment by bradlipovsky** [comment]
Jordi changed the sharing settings and so this should be resolved now!
